
import React from 'react';
import { Modal, Button } from './DesignSystem';
import { MarkdownView } from './MarkdownView';
import { FileText, CheckCircle2, ShieldAlert } from 'lucide-react';

interface ComplianceReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: string;
}

export const ComplianceReportModal: React.FC<ComplianceReportModalProps> = ({ isOpen, onClose, report }) => {
  return (
    <Modal 
      isOpen={isOpen} 
      onClose={onClose} 
      title="AI Governance Audit"
    >
      <div className="p-2 space-y-6">
        <div className="bg-indigo-50 dark:bg-indigo-900/20 border border-indigo-100 dark:border-indigo-800 rounded-xl p-4 flex items-start gap-4">
           <div className="p-2 bg-indigo-100 dark:bg-indigo-800 rounded-lg shrink-0">
              <FileText className="w-6 h-6 text-indigo-600 dark:text-indigo-300" />
           </div>
           <div>
              <h4 className="font-bold text-indigo-900 dark:text-indigo-100 text-sm">Executive Summary</h4>
              <p className="text-xs text-indigo-700 dark:text-indigo-300 mt-1 leading-relaxed">
                 The following report was generated by analyzing your entire resource inventory against standard FinOps and Security best practices.
              </p>
           </div>
        </div>

        <div className="prose prose-sm dark:prose-invert max-w-none bg-slate-50 dark:bg-slate-950/50 p-6 rounded-xl border border-slate-200 dark:border-slate-800">
           {report ? <MarkdownView content={report} /> : (
              <div className="flex flex-col items-center justify-center py-12 text-slate-400">
                 <ShieldAlert className="w-12 h-12 mb-2 opacity-50" />
                 <p>Report generation in progress or failed.</p>
              </div>
           )}
        </div>

        <div className="flex justify-end pt-4 border-t border-slate-200 dark:border-slate-800">
           <Button variant="primary" onClick={onClose} leftIcon={<CheckCircle2 className="w-4 h-4" />}>
              Acknowledge & Close
           </Button>
        </div>
      </div>
    </Modal>
  );
};
